---
services:
    stirling-pdf:
        container_name: stirling-pdf
        restart: unless-stopped
        image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
        ports:
            - '8080:8080'
        environment:
            - DISABLE_ADDITIONAL_FEATURES=false
            - DISABLE_PIXEL=true
            - LANGS=en_US
